### ISSUE TITLE
URIs of josd's reasoning rules changed 

### ISSUE THREAD

**Issue by knisterstern** [nie-ine/Rules#1]
Dear Hans,
Jos De Roo moved the folder "reasoning" to his brain project. All URIs referring to these
rules need to be changed. Change `eye/master/reasoning` to `brain/master`.

Regards,
Christian

**Comment by hanscools** [comment]
Dear Christian,
Thanks for letting me know.
I'll make changes accordingly.
Regards,
Hans

**Comment by josd** [comment]
Very well and I apologize for the inconvenience.
We are now developing 'BRAnches of INtelligence" as a new project called
BRAIN.

Kind regards,
Jos

-- https://josd.github.io/ <http://josd.github.io/>

**Comment by josd** [comment]
right now, after breaking too many links, we are back at eye/reasoning
https://github.com/josd/eye/tree/master/reasoning
https://github.com/josd/eye/blob/master/reasoning/README.md

Kind regards,
Jos

-- https://josd.github.io/ <http://josd.github.io/>
